### ISSUE TITLE
unwrap_or -> unwrapOr

### ISSUE THREAD

**Issue by linonetwo** [traverse1984/oxide.ts#1]
Will you consider this alternative alias, that is near to the JS community tradition?

**Comment by rrbutani** [comment]
@linonetwo I believe these camel-case aliases are already provided: [`Option`](https://github.com/traverse1984/oxide.ts/blob/77ed9707048c68c2cc98102675423ab297880ac3/src/monad/option.ts#L425-L437), [`Result`](https://github.com/traverse1984/oxide.ts/blob/77ed9707048c68c2cc98102675423ab297880ac3/src/monad/result.ts#L458-L471).

**Comment by traverse1984** [comment]
They are indeed already provided. Based on feedback from many people, they will likely become the default. The snake case versions may be removed or move to a require-by-choice extension.

**Comment by linonetwo** [comment]
Wow, I was just reading Readme, not installed yet, I will try it locally, thanks.
