### ISSUE TITLE
I think there should be a API for unwrapping Results into tuples

### ISSUE THREAD

**Issue by thelinuxlich** [traverse1984/oxide.ts#10]
So it would be something like:

```ts
const [err, res] = val.unwrapTuple() // golang style
```

**Comment by traverse1984** [comment]
I like the idea. Perhaps as `intoTuple` to fit with the current naming convention. I'll look to add this when I'm a little less busy, unless you want to make a PR.

**Comment by thelinuxlich** [comment]
yeah, intoTuple would be neat

**Comment by traverse1984** [comment]
`intoTuple` has been added in 1.1.0, which has been published to npm. Enjoy!
