### ISSUE TITLE
Unexpected Type Strictness with `unwrap_or`

### ISSUE THREAD

**Issue by alexlafroscia** [traverse1984/oxide.ts#2]
While checking out this library by trying to convert usage of `ts-results` to this package instead, I ran into an error with `unwrap_or`. The following code does not compile, though I would expect it should:

```typescript
import { type Option } from 'oxide.ts';

type Name = string | undefined;

interface User {
  name: Name;
}

declare function getName(person: User): Option<string>;

const name: Name = getName({ name: 'Alex' }).unwrapOr(undefined);
```

> Argument of type 'undefined' is not assignable to parameter of type 'string'.

[TypeScript Playground link](https://www.typescriptlang.org/play?ts=4.5.4#code/JYWwDg9gTgLgBAbzjAnmApnA8mGwIB2cAvnAGZQQhwDkEAHsACboB0MAzjQNwBQvqDHAByAQxCYAvHA4wowAgHM4AHzgBXAizIL0TPrwUx0UMqIDGmAKocTiXnDgFx6AFwiXfYvxbmANqJQmGSa5niEcIroMGISABQYUByE7jYmAJTuOOEEADyy8koAfAbmhLJOLu6xUpHRNXFIzhLuNACCfuj0NCTprJoA7lCiYFhQcZraukzp3EA)

It seems odd to me that `unwrap_or` would demand it's passed a value that matches the type of the `Option` that is being unwrapped. I can understand that maybe the types _should_ normally be the same, but not that this library has a strong opinion on the matter.

If _this_ was the code instead, I would expect an error to occur because `undefined` doesn't match the types expected by `Name`, but I would expect that the assignment itself would be the type error, not the usage of `unwrap_or`

```diff
import { type Option } from 'oxide.ts';

- type Name = string | undefined;
+ type Name = string;

interface User {
  name: Name;
}

declare function getName(person: User): Option<string>;

const name: Name = getName({ name: 'Alex' }).unwrapOr(undefined);
```

All that to say: I think that it would make sense that `unwrap_or` can accept _any_ value, and that the return type of `unwrap_or` becomes the union of the `Option`'s type and the `unwrap_or` argument's type. If they're the same, great! If they're not the same, that should be OK too.

**Comment by traverse1984** [comment]
Thanks for taking a look. This behaviour is as intended to match the [Rust implementation](https://doc.rust-lang.org/src/core/option.rs.html#750).

It's worth noting that `T | undefined` is similar to `Option<T>`. That might fit better here. 

If you definitely want this behaviour, you could technically use `unwrapUnchecked()` for the Option type, but it's not an idiomatic solution. You could also:

```ts
const p1 = getName({ name: "Alex" });
const name: Name = p1.is_some() ? p1.unwrap() : undefined;
```

Hopefully this makes sense and you can see how this scenario evades the purpose of the Option. Once you have the `Name` type you're back to `T | undefined` and will probably need another assertion later on, so holding at as an Option never actually helped.
